# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Summarize_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Summarize_app
  pod 'Alamofire', '~> 4.0'
  pod 'TaggerKit'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'WaterfallGrid', '~> 1.0.0'

  target 'Summarize_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Summarize_appUITests' do
    # Pods for testing
  end

end
